version: '3'

services:
    web:
        image: webdevops/php-nginx-dev:8.3
        restart: unless-stopped
        working_dir: /app
        ports:
            - "${APP_PORT:-80}:80"
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
        volumes:
            - ./:/app
        depends_on:
            - db
            - redis
            - mailpit
        env_file: .env

    db:
        image: mysql:9.0
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/db/dumps/:/dumps/
            - mysql_data:/var/lib/mysql
        ports:
            - "${DB_PORT:-3306}:3306"

    redis:
        image: redis:7.4.0
        restart: unless-stopped
        ports:
            - "${REDIS_PORT:-6379}:6379"
        volumes:
            - redis_data:/data

    mailpit:
        image: 'axllent/mailpit:latest'
        restart: unless-stopped
        ports:
            - '${MAIL_PORT:-1025}:1025'
            - '${MAIL_DASHBOARD_PORT:-8025}:8025'
        volumes:
            - mailpit_data:/data
        environment:
            MP_DATA_FILE: /data/mailpit.db

volumes:
    mysql_data:
    mailpit_data:
    redis_data:
